### ISSUE TITLE
What is the reason for reporting the following error when installing?

### ISSUE THREAD

**Issue by zlf123-marker** [MarcCote/tractconverter#43]
Collecting http://github.com/MarcCote/tractconverter/archive/master.zip
  Cache entry deserialization failed, entry ignored
  Downloading http://github.com/MarcCote/tractconverter/archive/master.zip
     / 81kB 206kB/s
    Complete output from command python setup.py egg_info:
    Downloading https://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Extracting in C:\Users\201904~1\AppData\Local\Temp\tmpxvutj8tx
    Traceback (most recent call last):
      File "C:\Users\201904~1\AppData\Local\Temp\pip-y6k502c8-build\distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\201904~1\AppData\Local\Temp\pip-y6k502c8-build\setup.py", line 13, in <module>
        distribute_setup.use_setuptools()
      File "C:\Users\201904~1\AppData\Local\Temp\pip-y6k502c8-build\distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "C:\Users\201904~1\AppData\Local\Temp\pip-y6k502c8-build\distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "C:\Users\201904~1\AppData\Local\Temp\pip-y6k502c8-build\distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "C:\Users\201904~1\AppData\Local\Temp\pip-y6k502c8-build\distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\201904~1\AppData\Local\Temp\pip-y6k502c8-build\

**Comment by MarcCote** [comment]
Which Python version are you using? TractConverter only supports Python 2.7.

Also, note that TractConverter has been deprecated in favor of Nibabel for a few years now.

**Comment by zlf123-marker** [comment]
Excuse me, besides this method, I would like to ask how to convert TRK files into VTK files?

**Comment by MarcCote** [comment]
Hi. I wouldn't use TractConverter to do the conversion. See the following for an example of how to covert TRK to VTK using Dipy
https://mail.python.org/pipermail/neuroimaging/2019-July/002006.html

**Comment by zlf123-marker** [comment]
Thank you so much
